/*
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class KukulkanStandaloneSetup extends KukulkanStandaloneSetupGenerated {

	def static void doSetup() {
		new KukulkanStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
